# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {U:/Computer Arch/VHDL_assignment/VHDL_assignment.cache/wt} [current_project]
set_property parent.project_path {U:/Computer Arch/VHDL_assignment/VHDL_assignment.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {u:/Computer Arch/VHDL_assignment/VHDL_assignment.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/arithmetic_circuit_16bit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/arithmetic_circuit_mux.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/arithmetic_logic_unit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/decoder_3to8.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/new/flags.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/full_adder.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/new/function_unit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/logic_unit_16bit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/mux2_16bit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/mux3_1bit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/mux4_16bit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/mux8_16bit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/reg.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/reg_file.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/ripple_carry_adder_16.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/imports/new/shifter_unit.vhd}
  {U:/Computer Arch/VHDL_assignment/VHDL_assignment.srcs/sources_1/new/datapath.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top datapath -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef datapath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file datapath_utilization_synth.rpt -pb datapath_utilization_synth.pb"
